# Generated by Django 4.2.11 on 2024-04-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(choices=[('AI', 'Alimentaire'), ('Mb', 'Meuble'), ('Sn', 'Sanitaire'), ('Vs', 'Vaisselle'), ('V', 'Vêtement'), ('Jx', 'Jouets'), ('L', 'Linge de Maison'), ('Bj', 'Bijoux'), ('Dc', 'Décor')], default='Alimentaire', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('AI', 'Alimentaire'), ('Mb', 'Meuble'), ('Sn', 'Sanitaire'), ('Vs', 'Vaisselle'), ('V', 'Vêtement'), ('Jx', 'Jouets'), ('L', 'Linge de Maison'), ('Bj', 'Bijoux'), ('Dc', 'Décor')], default='em', max_length=2),
        ),
    ]
